name: Shadow Build
on:
  push:
    branches:
      - 'build/**' # Auto-trigger when Python pushes the shadow branch
  workflow_dispatch: # Keeps the manual button option available

jobs:
  build:
    permissions:
      contents: write # Essential for deleting the branch at the end
    runs-on: [self-hosted, local-tester]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build and Run Test
        run: |
          gcc main.c -o test_app.exe
          .\test_app.exe
      - name: Simulate Compile
        run: |
          echo "Compiling..."
          echo "DONE: HEX GENERATED" > output.hex

      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: output.hex

      - name: Auto-Cleanup Branch
        if: always() # Runs even if the compile fails
        run: git push origin --delete ${{ github.ref_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}